# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trailtool < Formula
  desc "CLI for querying precomputed CloudTrail data — people, sessions, roles, services, resources"
  homepage "https://github.com/engseclabs/trailtool"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/engseclabs/trailtool/releases/download/v0.3.0/trailtool_0.3.0_darwin_amd64.tar.gz"
      sha256 "0ea162fda696e48c53efe80e27a78c971cb8a19dd31f350621f141366263a9ba"

      define_method(:install) do
        bin.install "trailtool"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/engseclabs/trailtool/releases/download/v0.3.0/trailtool_0.3.0_darwin_arm64.tar.gz"
      sha256 "832436c2a996eca04838707b7567613cc8206a5b8c80eb66f3e5094848f8798a"

      define_method(:install) do
        bin.install "trailtool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/engseclabs/trailtool/releases/download/v0.3.0/trailtool_0.3.0_linux_amd64.tar.gz"
      sha256 "bcbaa1b1408b200d8382e4ba2f3ef4459077fff2167be54c156e906bdf1e65d7"
      define_method(:install) do
        bin.install "trailtool"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/engseclabs/trailtool/releases/download/v0.3.0/trailtool_0.3.0_linux_arm64.tar.gz"
      sha256 "bfab5136d042b5ab95326b7c86446cad3c39b0922fe4c3b3e0f80814b8c00cca"
      define_method(:install) do
        bin.install "trailtool"
      end
    end
  end
end
