# This file was generated by GoReleaser. DO NOT EDIT.
cask "trailtool" do
  name "trailtool"
  desc "CLI for querying precomputed CloudTrail data — people, sessions, roles, services, resources"
  homepage "https://github.com/engseclabs/trailtool"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trailtool"

  on_macos do
    on_intel do
      url "https://github.com/engseclabs/trailtool/releases/download/v#{version}/trailtool_#{version}_darwin_amd64.tar.gz"
      sha256 "cb32002c4f42975df04b9f7ac5c14c51be84e08d6c4590b8463aef74d10f27ee"
    end
    on_arm do
      url "https://github.com/engseclabs/trailtool/releases/download/v#{version}/trailtool_#{version}_darwin_arm64.tar.gz"
      sha256 "68ba1afbbfa4ecf8199a8aa581836ae2b2291b435dd7dcaf27d9f8ccc7ba7cb2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/engseclabs/trailtool/releases/download/v#{version}/trailtool_#{version}_linux_amd64.tar.gz"
      sha256 "02313c164fd915f32fd02f931bbb5403e6bfdbd6348b3ff624f5975294ac4f49"
    end
    on_arm do
      url "https://github.com/engseclabs/trailtool/releases/download/v#{version}/trailtool_#{version}_linux_arm64.tar.gz"
      sha256 "378e1fb905e6559b2bd4b4dded446f997f4422fe217e017a47bf77f8fe2359bf"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/trailtool"]
  end

  caveats do
    "trailtool is not yet code-signed. macOS may block it on first run."
    "If that happens, run: xattr -d com.apple.quarantine $(which trailtool)"
  end

  # No zap stanza required
end
