# This file was generated by GoReleaser. DO NOT EDIT.
cask "trailtool" do
  name "trailtool"
  desc "CLI for querying precomputed CloudTrail data — people, sessions, roles, services, resources"
  homepage "https://github.com/engseclabs/trailtool"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trailtool"

  on_macos do
    on_intel do
      url "https://github.com/engseclabs/trailtool/releases/download/v#{version}/trailtool_#{version}_darwin_amd64.tar.gz"
      sha256 "25da37d47aa87e52d024b75211f91c86fb1e0a7d3b223b9c8f8ce9b806441f8f"
    end
    on_arm do
      url "https://github.com/engseclabs/trailtool/releases/download/v#{version}/trailtool_#{version}_darwin_arm64.tar.gz"
      sha256 "ae416f96ecfa4a0da67d58cf8fd91a94771a414e1c981694d7ecc6bc63c929df"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/engseclabs/trailtool/releases/download/v#{version}/trailtool_#{version}_linux_amd64.tar.gz"
      sha256 "f368c58ac15bbea3bb8a66d008a07e577fed4ea4703146be482f7c64174a5ccc"
    end
    on_arm do
      url "https://github.com/engseclabs/trailtool/releases/download/v#{version}/trailtool_#{version}_linux_arm64.tar.gz"
      sha256 "9f1c72becac72f27cca8f86475ad9deb9c09661c6e60bfe104839178041d9cff"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/trailtool"]
  end

  caveats do
    "trailtool is not yet code-signed. macOS may block it on first run."
    "If that happens, run: xattr -d com.apple.quarantine $(which trailtool)"
  end

  # No zap stanza required
end
